### ISSUE TITLE
Tested on [LG] webOS TV OLED65B6P

### ISSUE THREAD

**Issue by ThingEngineer** [FeLiNa22/amazon-alexa-lg-tv#10]
Tested on [LG] webOS TV OLED65B6P - works great!

Any idea what (if possible) the wording is for the Alexa command to open an app like YouTube or Netflix? These apps do show up in applists.json .

**Comment by FeLiNa22** [comment]
Hi @ThingEngineer you would have to look into the LG TV API for this.

**Comment by ThingEngineer** [comment]
Looks like sinric does not support the '[Launch Targets](https://developer.amazon.com/docs/video/launch-target-reference.html)' video skill api so I would have to start there and work back through the LGWebOSRemote. Bummer that sinric is not open source.

Anyway, thank you for this!
