### ISSUE TITLE
The initiating new websocket connection doens't work

### ISSUE THREAD

**Issue by lhoram** [FeLiNa22/amazon-alexa-lg-tv#11]
Hi , i did every step and at the Initiating new websocket connection, it doesn't respond , would be it looking for the tv?

**Comment by lhoram** [comment]
i got an erro 
messy : {"deviceId":"5de013720eaca743532451f6","action":"setPowerState","value":"OFF"}
/proc/net/arp: No such file or directory

do i need to do all it again?

**Comment by FeLiNa22** [comment]
This seems to be an issue with WSL and not the script itself. Looking at a quick google of the error you are recieving I would recommend using WSL2
