### ISSUE TITLE
Test on Uh661

### ISSUE THREAD

**Issue by Crasso91** [FeLiNa22/amazon-alexa-lg-tv#12]
Hi first of all thx you for giving us a bridge to work with our 'obsolete' tv.
I'm having problem on changeChannel:
![image](https://user-images.githubusercontent.com/15816319/69962593-a0d10600-150e-11ea-9e8f-fe1bc141e35d.png)

**Comment by FeLiNa22** [comment]
Hi Crasso91, 
Sorry, it has taken so long for me to get back to you.
The changing channel command is a bit of a nuisance,
I think you have to  say "Set Channel {Channel number}"
rather than "Change Channel"
