### ISSUE TITLE
Can not find TV when TV is connected to a device running the script

### ISSUE THREAD

**Issue by TJJP** [FeLiNa22/amazon-alexa-lg-tv#16]
I have a router running on a raspberry pi and I have this Lg tv controller on the same device. When I have the TV connected to the main network this program works fine. I have my phone connected to the subnetwork router on the pi so I would also like the tv connected to that same network so I can easily use the Lg tv app. When I run the setup.py it cannot find the tv even when typing in the IP address or localhost. Is there any way to do this?

**Comment by FeLiNa22** [comment]
All devices involved must be on the same network; for your setup, I would believe the Alexa device, TV and script would be running through the raspberry pi's router. If you also try to set up the script on this same raspberry Pi it will not work, as this raspberry pi is using your external network connection and not it's own one.
