### ISSUE TITLE
Power ON don't work

### ISSUE THREAD

**Issue by AlexandreVassard** [FeLiNa22/amazon-alexa-lg-tv#17]
Hello, everything is fine on my tv.
I putted on the wake on lan.
TV is connected by ethernet

**Comment by FeLiNa22** [comment]
Have you tried turning off fast-startup on the TV?

**Comment by AlexandreVassard** [comment]
Edit; sorry i didn't understand.
I don't have this option on my tv

**Comment by FeLiNa22** [comment]
Okay, are all the other commands working, and just not the power on ?

**Comment by Vsdparibas** [comment]
Everything is good.
I found why i had this problem.
If i just turned off the tv, i have to wait 2-3 minutes that it really turns off.
After that i can turn the tv on with alexa.
There's like a standby mode before the tv turns off, and in standby you can't turn on with alexa.
So all of commands work, and thank you for your really great work.

Edit: sorry again, wrong account but it's me again

**Comment by FeLiNa22** [comment]
Ahh, no problem 👍
