### ISSUE TITLE
Syntax error running Alexa.py

### ISSUE THREAD

**Issue by outoftheblue62** [FeLiNa22/amazon-alexa-lg-tv#2]
Hi FeLiNa22 - Opening a new issue as I received the following syntax error when running python Alexa.py (after running setup.py and entering my sinric API key in line 80):

  File "Alexa.py", line 81
    ws = websocket.WebSocketApp("ws://iot.sinric.com/",header={'Authorization:' +  base64.b64encode('apikey:   +' api '+      ')},on_message = on_message,on_error = on_error, on_close = on_close)
                                                                                                                    ^
SyntaxError: invalid syntax

**Comment by FeLiNa22** [comment]
No problem outoftheblue62, 
Thank you for recognising this as I made a very stupid syntax mistake.
I have uploaded a new version of the Alexa.py file, which with a bit of luck should run perfectly now.

Also I am sorry for the late response, I have been working on another project all day :(

**Comment by outoftheblue62** [comment]
That did it, thank you so much!  Closing this issue
