### ISSUE TITLE
promting allow to connect every request

### ISSUE THREAD

**Issue by masatmarek** [FeLiNa22/amazon-alexa-lg-tv#4]
Hi,

I succesfully made this app working with alexa, but the only problem is that every time I ask alexa to  do something with tv there is a promt on my tv to allow access for the app.

**Comment by FeLiNa22** [comment]
Hi masatmarek sftlr, 

try running setup.py script as the sudo/administrator account

if on linux use:
        sudo python setup.py
if on windows:
        run cmd in admin mode

and make sure to authenticate on your tv when it prompts you. lmk if this works.

**Comment by FeLiNa22** [comment]
Hi masatmarek,
seeing as this issue is now quite old, I have assumed that you have fixed this problem, and will now close the report.
