### ISSUE TITLE
Not working after all steps

### ISSUE THREAD

**Issue by elnikodemo** [FeLiNa22/amazon-alexa-lg-tv#6]
Hi there!,
 
 I followed all instruction, I authorized the app in my TV. The device is recognized in Alexa, but when I say some instruction, nothing happen on the tv and Alexa says "ok". In the shell I have the following lines:

### Initiating new websocket connection ###
messy : {"deviceId":"5cb11c6e9f58230ab4c3c525","action":"setPowerState","value":"OFF"}
messy : {"deviceId":"5cb11c6e9f58230ab4c3c525","action":"setPowerState","value":"OFF"}
messy : {"deviceId":"5cb11c6e9f58230ab4c3c525","action":"SetVolume","value":{"volume":10}}
messy : {"deviceId":"5cb11c6e9f58230ab4c3c525","action":"SetVolume","value":{"volume":0}}

Something to do extra or again??

regards!

**Comment by FeLiNa22** [comment]
Hi elnikodemo,

I would advise trying to run the setup.py script again (make sure you are running as root/sudo),
make sure the TV is on through this whole process, even when running the Alexa.py script.

If the issue continues to persist, it may be that the local firewall/router is preventing any communication between the device running the program and the Alexa device.
