### ISSUE TITLE
Syntax eroror

### ISSUE THREAD

**Issue by sudo-kraken** [FeLiNa22/amazon-alexa-lg-tv#7]
I am running this in a Windows environment, I have installed node.js and python successfully installed all the requirements however when it comes to running the setup.py script it imports the LG module then fails on line 113 complaining about syntax with the brackets, please can someone advise who has this working in a Windows env.

Thanks

**Comment by FeLiNa22** [comment]
This module was only designed to work with python 2 and not python 3

**Comment by sudo-kraken** [comment]
Confirmed working on LG 43uh620v
