### ISSUE TITLE
Can't turn on TV again

### ISSUE THREAD

**Issue by lhj2387** [FeLiNa22/amazon-alexa-lg-tv#9]
Hi, 
Thank you for your amazing Alexa LG tv remote :)
Generally, most functions work well but I found that I can't turn on the TV after off
I know this issue happened before, but It happens again that reporting here

messy : {"deviceId":"5da2a92ca0866720351af2cd","action":"setPowerState","value":"OFF"}
{"type": "response", "id": "0", "payload": {"returnValue": true}}
{"closing": {"reason": "server shutting down", "code": 1001}}

messy : {"deviceId":"5da2a92ca0866720351af2cd","action":"setPowerState","value":"ON"}
ERROR LOL : [Errno 54] Connection reset by peer
### closed ###

It seems the main problem is a "connection" 
May I ask how to solve this issue? (I know you don't handle this project anymore :( So, I apologise)

Thank you

**Comment by FeLiNa22** [comment]
Hi lhj2387 , 
It is most likely a fault in one of the deprecated libraries, I would suggest solving this, by adding a try ... except statement in the Alexa.py script, to retry connecting every 30 seconds.

**Comment by lhj2387** [comment]
> Hi lhj2387 ,
> It is most likely a fault in one of the deprecated libraries, I would suggest solving this, by adding a try ... except statement in the Alexa.py script, to retry connecting every 30 seconds.

Hi FeLiNa22
Thank you for your quick response.
If you don't mind, may I ask where to put try&except statement in Alexa.py?
I appreciate your help in advance :)

**Comment by FeLiNa22** [comment]
I would suggest wrapping it around this function 

def initiate():
    #websocket.enableTrace(True)
    api = ' enter-api-here  '
    ws = websocket.WebSocketApp("ws://iot.sinric.com/",header={'Authorization:' +  base64.b64encode('apikey:   '+ api +'      ')},on_message = on_message,on_error = on_error, on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()

**Comment by lhoram** [comment]
Hi FeLiNa22, i'm from brazil, it that too much you could improve your code to Sinric Pro? The normal Sinric doesn't work here , the skill is not available =/
